file:
  upload-dir: ./resume

spring:
  application:
    name: JobPortalWebsite

  datasource:
    url: jdbc:mysql://localhost:3306/jobportal
    username: jobportal
    password: jobportal

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
  servlet:
    context-path: /jobportal

jwt:
  signerKey: "bfHUHsKlqkHWujMxhcqkAgQzYmrQ1atDEUQ/q751h+tZ/Q6zfl32svrxukVz787F"